// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Mihajasoa",
            "email": "mihajasoaalain85@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/game": {
            "post": {
                "description": "Crée une nouvelle partie de Shifumi et renvoie les détails de la partie créée.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Créer une nouvelle partie",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shifumi_internal_models.Game"
                        }
                    }
                }
            }
        },
        "/game/{id}": {
            "get": {
                "description": "Récupère les détails d'une partie spécifique en utilisant son ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Obtenir les détails d'une partie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la partie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shifumi_internal_models.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/game/{id}/join": {
            "post": {
                "description": "Permet à un joueur de rejoindre une partie existante en fournissant un nom d'utilisateur.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Rejoindre une partie existante",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la partie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Requête pour rejoindre une partie",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shifumi_internal_models.JoinGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shifumi_internal_models.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Renvoie un statut 200 si le service Shifumi est opérationnel.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Vérifier la santé de l'API",
                "responses": {
                    "200": {
                        "description": "Exemple: {\"message\": \"work well\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "shifumi_internal_models.Game": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shifumi_internal_models.Player"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "shifumi_internal_models.JoinGameRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "shifumi_internal_models.Player": {
            "type": "object",
            "properties": {
                "choice": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shifumi API",
	Description:      "API pour le jeu Shifumi (Pierre-Papier-Ciseaux).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
