basePath: /
definitions:
  shifumi_internal_models.Choice:
    enum:
    - rock
    - paper
    - scissors
    type: string
    x-enum-varnames:
    - Rock
    - Paper
    - Scissors
  shifumi_internal_models.Game:
    properties:
      id:
        type: string
      players:
        items:
          $ref: '#/definitions/shifumi_internal_models.Player'
        type: array
      status:
        $ref: '#/definitions/shifumi_internal_models.GameStatus'
    type: object
  shifumi_internal_models.GameStatus:
    enum:
    - waiting
    - ready
    - playing
    type: string
    x-enum-varnames:
    - Waiting
    - Ready
    - Playing
  shifumi_internal_models.JoinGameRequest:
    properties:
      username:
        type: string
    type: object
  shifumi_internal_models.PlayRequest:
    properties:
      choice:
        $ref: '#/definitions/shifumi_internal_models.Choice'
      username:
        type: string
    type: object
  shifumi_internal_models.Player:
    properties:
      choice:
        $ref: '#/definitions/shifumi_internal_models.Choice'
      score:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: mihajasoaalain85@gmail.com
    name: Mihajasoa
  description: API pour le jeu Shifumi (Pierre-Papier-Ciseaux).
  title: Shifumi API
  version: "1.0"
paths:
  /game:
    post:
      description: Crée une nouvelle partie de Shifumi et renvoie les détails de la
        partie créée.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shifumi_internal_models.Game'
      summary: Créer une nouvelle partie
      tags:
      - Game
  /game/{id}:
    get:
      description: Récupère les détails d'une partie de Shifumi en fonction de son
        ID.
      parameters:
      - description: ID de la partie
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shifumi_internal_models.Game'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtenir les détails d'une partie
      tags:
      - Game
  /game/{id}/join:
    post:
      consumes:
      - application/json
      description: Permet à un joueur de rejoindre une partie existante en fournissant
        un nom d'utilisateur.
      parameters:
      - description: ID de la partie
        in: path
        name: id
        required: true
        type: string
      - description: Requête pour rejoindre une partie
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/shifumi_internal_models.JoinGameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shifumi_internal_models.Game'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Rejoindre une partie existante
      tags:
      - Game
  /game/{id}/play:
    post:
      consumes:
      - application/json
      description: Permet à un joueur de jouer un tour de Shifumi en fournissant son
        choix (pierre, papier ou ciseaux).
      parameters:
      - description: ID de la partie
        in: path
        name: id
        required: true
        type: string
      - description: Requête pour jouer un tour
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/shifumi_internal_models.PlayRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shifumi_internal_models.Game'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Jouer un tour de Shifumi
      tags:
      - Game
  /health:
    get:
      description: Renvoie un statut 200 si le service Shifumi est opérationnel.
      produces:
      - application/json
      responses:
        "200":
          description: 'Exemple: {"message": "work well"}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Vérifier la santé de l'API
      tags:
      - System
swagger: "2.0"
